version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - carteira_net

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - carteira_net

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: carteira
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - carteira_net

  node:
    image: node:20
    volumes:
      - ./src:/app
    working_dir: /app
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
      - "5174:5174"
    networks:
      - carteira_net

networks:
  carteira_net:
    driver: bridge

volumes:
  db_data: